### ISSUE TITLE
Links in embedded twitter widget open strange external browser window

### ISSUE THREAD

**Issue by jforaker** [romanschejbal/electron-blog#2]
Hello, this is not so much an issue with the repo as it is a question, I hope you might be able to lend some insight...

I have a similar implementation to the hackernews feed, but i show a list of tweets using the twitter sdk. When I click on a link within a tweet, the menubar app closes and it opens a strange browser window with no "chrome" (no close/minimize buttons). And the only way to close it is to quit the application. 

Any thoughts?  I was going to post this in the menubar repo but it looks like the author is unresponsive to all activity there.

![image](https://user-images.githubusercontent.com/2042031/27512014-67b3ac22-5901-11e7-93f4-01a633444fad.png)

**Comment by romanschejbal** [comment]
Are you using the electron shell to open the external link? As I'm doing [here](https://github.com/romanschejbal/electron-blog/blob/master/src/components/story/index.jsx#L29)

**Comment by jforaker** [comment]
For regular links, yes. But in this case, the links are part of the widget added by the twitter js sdk. 

![image](https://user-images.githubusercontent.com/2042031/27750413-b0dc2264-5da5-11e7-9ff3-77cc9b34a37b.png)

Which are ultimately rendered like this:
![image](https://user-images.githubusercontent.com/2042031/27750552-4ba68956-5da6-11e7-8daa-44bda1fbd629.png)

**Comment by romanschejbal** [comment]
I see. Well, you could find all the anchor elements once the content's loaded and attach your own onclick handler on them. The custom handler would prevent the default behaviour and open the link via electron's shell. Let me know if you need more help.

**Comment by jforaker** [comment]
Good idea. A bit of a challenge though because they are iframes 😱 .  I'll keep you posted. Thanks

**Comment by jforaker** [comment]
Wowzer I fixed it!
Did some smart googling and found [this](https://github.com/unfoldingWord-dev/ts-desktop/issues/458) which led to [this glorious thread](https://github.com/electron/electron/issues/1344#issuecomment-208839713).

So, I adjusted it and added that bit here:

```javascript
mb.on('after-create-window', function () {
  // https://github.com/marcbachmann/electron-rpc
  server.configure(mb.window.webContents);
  // https://github.com/romanschejbal/electron-blog/issues/2
  // and https://github.com/electron/electron/issues/1344#issuecomment-208839713
  const handleRedirect = (e, url) => {
    if (url !== mb.window.webContents.getURL()) {
      e.preventDefault();
      shell.openExternal(url)
    }
  };
  mb.window.webContents.on('will-navigate', handleRedirect);
  mb.window.webContents.on('new-window', handleRedirect);
});
```

And 🎉  clicking any anchor tag on an embedded tweet opens in my default browser and focuses itself on that tab. Perfecto. 

Closing.

Thanks again

**Comment by romanschejbal** [comment]
Great job! Thanks for sharing 👍
